# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qIT5d2bzfV8j-iU9ZHNEFS7SrtPlN1Vp
"""

import pandas as pd

df = pd.read_csv("imdb_top_1000.csv")

print(df.head())
print(df.info())

df['IMDB_Rating'] = pd.to_numeric(df['IMDB_Rating'], errors='coerce')
df['Released_Year'] = pd.to_numeric(df['Released_Year'], errors='coerce')
df['Runtime'] = pd.to_numeric(df['Runtime'].str.replace(' min',''), errors='coerce')

df = df.dropna(subset=['IMDB_Rating', 'Released_Year', 'Runtime'])

genre_ratings = df.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False)
print(genre_ratings)

top_10_movies = df.sort_values(by='IMDB_Rating', ascending=False).head(10)
print(top_10_movies[['Series_Title', 'Released_Year', 'IMDB_Rating', 'Genre']])

correlation_matrix = df[['IMDB_Rating', 'Released_Year', 'Runtime']].corr()
print(correlation_matrix)

actor_name = "Leonardo DiCaprio"
director_name = "Christopher Nolan"

movies_by_actor = df[
    df[['Star1','Star2','Star3','Star4']]
    .apply(lambda x: x.str.contains(actor_name, case=False, na=False))
    .any(axis=1)
]

print(movies_by_actor[['Series_Title', 'Released_Year', 'IMDB_Rating']])

movies_by_director = df[df['Director'].str.contains(director_name, case=False, na=False)]
print(movies_by_director[['Series_Title', 'Released_Year', 'IMDB_Rating']])